openapi: 3.0.1
info:
  title: monster-displacer-beast
  x-cortex-tag: monster-displacer-beast
  x-cortex-custom-metadata:
    alignment: lawful-evil
    type: monstrosity
    challenge_rating: 3
    legendary: false
    source: dnd-5e
  x-cortex-type: monster
  x-cortex-git:
    github:
      repository: xycia-cortex/monster-displacer-beast
      alias: github-token-test
